server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/url_db
    password: 22062005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true


